### ISSUE TITLE
Move instruction not supported for C.

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/verse-coq#33]
It seems that the move instruction `X <== A[i]` is not supported. Any reason for this.

**Comment by piyush-kurur** [comment]
@dangabhi

**Comment by dangabhi** [comment]
I thought destructing an array value would violate the integrity of the array specification in a sense. An array declared littleE should not suddenly have 'good' values at most indices and 'garbage' at one. A local track of destructed values can be kept and adhered to, but this kinda affects things outside the scope of our checks too right.
I assumed thus that all arch's would only use the non-destructing assign with rvals dereferenced. So that does not even hamper portability of code for archs that can actually support mov without destruct (a la C).

**Comment by piyush-kurur** [comment]
On Tue, Jan 30, 2018 at 07:40:06AM -0800, dangabhi wrote:
> I thought destructing an array value would violate the integrity of the array specification in a sense. An array declared littleE should not suddenly have 'good' values at most indices and 'garbage' at one. A local track of destructed values can be kept and adhered to, but this kinda affects things outside the scope of our checks too right.
> I assumed thus that all arch's would only use the non-destructing assign with rvals dereferenced. So that does not even hamper portability of code for archs that can actually support mov without destruct (a la C).


When there is a `C <= A[i]`. `A[i]` does not get destructed because we
first load then byteswap if necessary (depending on the endianness). On the
other hand an instruction like `A[i] <= C` requires first a bytesway and then
a store. So the byteswap happens only on the register side. In other words the
former instruction becomes (in pseudo assembly)

```
load A,i,C  # NO harm on A[i]
byteSwap C
```

where as the latter becomes

```
byteSwap C  # damage done to C
store C,A,i
```

**Comment by dangabhi** [comment]
That which you say is exactly my understanding and the reason behind the choice. If an instruction is not going to destruct the rval then it should not be using 'mov' at all. It should always be 'C ::== A[i]' across all architectures. 
So, either both 'C <= A[i]' and 'C ::== A[i]' would have the same semantics across all architectures or I would have to destruct A[i] on use of 'C <= A[i]' in generic code. Neither seems like a good alternative.

**Comment by piyush-kurur** [comment]
The point is how you read the move sematics. I read it as it *may* damage the source but definitely not the destination. You seem to read it as it *will* damage the source.

**Comment by dangabhi** [comment]
Not really no. 'May' is fine, but not 'never'. If 'C <= A[i]' _never_ destructs A[i] then it should not be a 'mov' - that is more my point.

**Comment by piyush-kurur** [comment]
On Tue, Jan 30, 2018 at 10:48:21PM -0800, dangabhi wrote:
> Not really no. 'May' is fine, but not 'never'. If 'C <= A[i]' _never_ destructs A[i] then it should not be a 'mov' - that is more my point.

Let me argue it the other way. If I replace all moves with copies that
is not going to make the program incorrect. So as long as copy is
"supported" move should also be supported. It is just that move can be
more efficient and by writing move instead of copy, I am saying that I
do not care to use the result of the source so feel free to do the transfer
more efficiently even if it destructs the source.

A destination is never destructed in that sense as we now have new
value in the destination no matter what.

**Comment by dangabhi** [comment]
So, I guess your read is 'mov' is the default 'A = B' instruction and copy is to be used only when you really want to make sure that rval is preserved, and it might not be. Which is not the case when 'B <= A[i]', as in A[i] will never be destructed and thus does not _need_ a 'copy'.
Confirm, and I will make the change (the destruct semantics will ignore this version of the mov instruction).

**Comment by piyush-kurur** [comment]
In addition destruction can only happen on the register side not on the memory side. The problem is I am not yet clear how one is going to enforce this understanding, particularly on the generic code. I think what we can do currently is not to enforce but only give translation. May be we can discuss this over IRC today afternoon.

**Comment by piyush-kurur** [comment]
I think this issue is now no more relevant. The conclusion is that move instructions are supported in C.
