### ISSUE TITLE
Adjusting the definition of assignment and instructions.

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/verse-coq#35]
@dangabhi Does it make more sense to change the definitions of assignment and instructions thus:

```
Inductive assignment (v : VariableT) : Type :=
        | assign3 : forall ty, binop -> v direct ty -> v direct ty -> v direct ty -> assignment v
        blah blah blah

Inductive instruction (v : VariableT) :=
    | assign (assignment (arg v)) ->....
```

i.e. assignment is defined for any generic variable and the wrapping it in argv happens at the instruction level. Will this simplify some nesting?

I am not sure whether this was discussed before so I am putting this up.

**Comment by piyush-kurur** [comment]
Infact it can even be moved one step up both instruction and assignment are using generic variables
but only

```
 Definition block v := list (instruction (arg v)) 
```

**Comment by dangabhi** [comment]
This does not affect the nesting at all. Infact might make some things harder. All checks anyway (lval-not-constant, endian-error, deref-not-here) cannot be done at the generic variable level. And in
`match i with
| assign a => match a with ***`
I am pretty sure the second match will have forgotten that the assignment was over an arg.

**Comment by piyush-kurur** [comment]
No more relevant.
