### ISSUE TITLE
8 bit multiplication

### ISSUE THREAD

**Issue by dangabhi** [raaz-crypto/verse-coq#43]
8-bit multiplication works as `AX <- AL * r/m8`
Luckily, AH is accessible as a standalone register, and I can fit this into ext-mul as -
`AH:AL <- AL * r/m8`
However, that does not then allow the user to use AX as the 16-bit result. @piyush-kurur do weigh in on issue, if it is one.

**Comment by piyush-kurur** [comment]
On Tue, Feb 27, 2018 at 05:18:23PM +0000, dangabhi wrote:
> 8-bit multiplication works as `AX <- AL * r/m8`
> Luckily, AH is accessible as a standalone register, and I can fit this into ext-mul as -
> `AH:AL <- AL * r/m8`
> However, that does not then allow the user to use AX as the 16-bit result. @piyush-kurur do weigh in on issue, if it is one.
>

Yes this is an issue that is a problem with x86 architectures. I guess
there is a 16-bit multiplication as well of a similar kind and on
x86_64, there is a 32 bit multiplication. We would have to assume that
these instructions use the entire A register (64-bit/32 bit depending
on the architecture).

There are couple of options

1. We can think of them as special multiplication instructions.

2. We might want to work with some kind of interface for register
   slices. Remember that the register of a machine is a VariableT so
   it can be a slice of a register. However we will need to ensure
   that we do not allocate a single register both as a slice and also
   as a full register.

This needs discussion. May be we can avoid these problematic
instructions for time being. However, I see that the 32-bit variant of
this instruction could be quite useful.

**Comment by dangabhi** [comment]
I should have been clearer - 8-bit multiplication is unique here.
Since the only non-lowest-bits addressable as a register are 8-15 (AH/BH), 8-bit multiplication works as `AH:AL <- AL * r/m8`. Others use the D register for higher bits - 16-bit multiplication (for eg.) would go as `DX:AX <- AX * r/m16`. 
However, if we want to be able to access the full result as a single operand later then we technically already have it available for the 16-bit result (use AX), and for 16-bit multiplication we would have to 
mask-high-half of EDX; shift EDX left by 16; mask-high-half of EAX; add EAX EDX
even when writing code in assembly itself.
While this instruction sequence can be written in Verse, the problem is that we need a typecast operation to be able to ever use this value. The way Verse works, instructions operating on Word16 and Word32 are disjoint and can never interact in values/registers.
I'll try to think of a way to provide a pseudo-type-cast using a pair-like-arg and/or by using an instruction that does not have all operands of the same type. Just for now, I don't allow 8-bit multiplication mostly cause I don't have a good encoding of AH in the registers :)

**Comment by piyush-kurur** [comment]
On Wed, Feb 28, 2018 at 05:27:36AM +0000, dangabhi wrote:
> I should have been clearer - 8-bit multiplication is unique here.
> Since the only non-lowest-bits addressable as a register are 8-15 (AH/BH), 8-bit multiplication works as `AH:AL <- AL * r/m8`. Others use the D register for higher bits - 16-bit multiplication (for eg.) would go as `DX:AX <- AX * r/m16`. 
> However, if we want to be able to access the full result as a single operand later then we technically already have it available for the 16-bit result (use AX), and for 16-bit multiplication we would have to 
> mask-high-half of EDX; shift EDX left by 16; mask-high-half of EAX; add EAX EDX
> even when writing code in assembly itself.
> While this instruction sequence can be written in Verse, the problem is that we need a typecast operation to be able to ever use this value. The way Verse works, instructions operating on Word16 and Word32 are disjoint and can never interact in values/registers.
> I'll try to think of a way to provide a pseudo-type-cast using a pair-like-arg and/or by using an instruction that does not have all operands of the same type. Just for now, I don't allow 8-bit multiplication mostly cause I don't have a good encoding of AH in the registers :)
>


My suggestion is to drop support for such instructions for time
being. We can think of this for later so that we stick to the
deadline.

**Comment by piyush-kurur** [comment]
Very little need for these type of instructions in modern crypto implmentations. Let us drop it.
