### ISSUE TITLE
Explore 'Program Definition'

### ISSUE THREAD

**Issue by dangabhi** [raaz-crypto/verse-coq#54]
'Program Definition' with a custom 'Obligation Tactic' can replace Definitions done in proof mode.
Example: 
`Local Obligation Tactic := (Tactics.program_simpl + 
                                                            intros; apply	NPeano.Nat.mod_upper_bound; omega).`
followed by a 'Program Definition' avoids the verse tactic for bound checking involving simple mod-bounds.

**Comment by piyush-kurur** [comment]
Not relevant any more
