### ISSUE TITLE
Add bounds checking for shift operations

### ISSUE THREAD

**Issue by SooryaN** [raaz-crypto/verse-coq#58]
The generated code presently has segments like this. 
``` C
register uint16_t rtemp;

rtemp = verse_form_be16(p0[1]) << 42; //shift count > width of type
rtemp = verse_form_be16(p0[1]) >> 42; //shift count > width of type
```
Where the shift count is > then the width of the type. A check needs to be added to prevent the same.

**Comment by piyush-kurur** [comment]
What does masking mean in the X86 context ? Shifting by an amount greater than the bit size results in all zeros I guess. In any case I think we should disallow shifts greater than word size in Verse. This could be done pretty much the same way as we do for array bounds currently.

Some points to note. Word n type denotes word of 2^n bytes, so we would want the shift amount to be less than 2^(n+3). @dangabhi May be we might need reflection to make this efficient as the proof terms will now be part of the verse Ast.

**Comment by piyush-kurur** [comment]
This particular update might require a slightly different design and hence can be tricky as @dangabhi mentioned in a phone call to me. We will keep this aside for now.

**Comment by dangabhi** [comment]
https://github.com/piyush-kurur/verse-coq/blob/5fdb7e0d540532b563728c3e7e440f8176fcf53a/src/Verse/Language/Operators.v#L131-L136
There is no reason why we should define a lift of `wordOpDenote` to `array`'s, is there? Our AST only allows instructions to work on direct types.
This comes up in the context of this issue.
